name: "Storcube Stacker Bridge"
description: "Récupère les données des batteries Storcube Stacker via WebSocket et les envoie vers MQTT."
version: "1.0.0"
slug: "storcube_stacker_bridge"
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  MQTT_BROKER: "192.168.1.XX"
  MQTT_PORT: 1883
  MQTT_USERNAME: "mqtt_user"
  MQTT_PASSWORD: "mqtt_password"
  LOGIN_NAME: "votre_email"
  PASSWORD: "votre_password"
  DEVICE_ID: "votre_id"
schema:
  MQTT_BROKER: str
  MQTT_PORT: int
  MQTT_USERNAME: str
  MQTT_PASSWORD: str
  LOGIN_NAME: str
  PASSWORD: str
  DEVICE_ID: str
